INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (1, 'Alan Turing', 'Mathematician, Enigma decryptor', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (2, 'Ada Lovelace', 'First computer program', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (3, 'Dennis Ritchie', 'Creator of C and co-creator of UNIX', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (4, 'Donald Knuth', 'The Art of Computer Programming', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (5, 'Joan Clarke', 'Enigma co-decryptor', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (6, 'John Von Neumann', 'Processor architecture', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (7, 'Linus Torvalds', 'Linux', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (8, 'Richard Stallman', 'FSF, GNU', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (9, 'Eric S Raymond', 'The cathedral and bazaar', '')
INSERT INTO PERSON("id", "name", "description", "imageurl") VALUES (10, 'Tim Berners-Lee', 'WWW', '')
